on: 
  workflow_dispatch:
  
jobs:
#   build:
#     name: Build go app
#     runs-on: ubuntu-latest
#     steps:
#       - name: to checkout
#         uses: actions/checkout@v2

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1
        
#       - name: Set up Go
#         uses: actions/setup-go@v3
#         with:
#           go-version: 1.15   
      
#       - name: to build 
#         uses: virtuecloud/Composite-actions/Build/go@test
#         with:
#           DEPENDENCY_REQUIRED: false
#           BUILD_PATH: .

  deploy:
    name: Deploy to ec2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: upload to s3
        run: aws s3 sync ./ s3://flask-buckett --delete 
        
        
      - name: AWS SSM Send-Command
        run: aws ssm send-command --document-name "AWS-RunRemoteScript" --instance-ids "i-0bc9ff54f414b5e1c" --parameters '{"sourceType":["S3"],"sourceInfo":["{\"path\":\"https://rennn.s3.us-east-1.amazonaws.com\"}"],"commandLine":["sudo bash a.sh"],"workingDirectory":["/home/ubunntu"]}'     
        shell: bash  
